SET IDENTITY_INSERT dbo.Category ON
GO

MERGE INTO dbo.Category AS TARGET
USING (VALUES 
              -- Fact Categories
              ( 1, 1, 'Science'),
              ( 2, 1, 'Space'),
              ( 3, 1, 'Geology'),
              ( 4, 1, 'History'),
              ( 5, 1, 'Military'),
              ( 6, 1, 'Biology'),
              ( 7, 1, 'Animals'),
              ( 8, 1, 'Geography'),
              ( 9, 1, 'Food'),
              (10, 1, 'Archeology'),
              (11, 1, 'Life'),
              (12, 1, 'Statistics'),
              (13, 1, 'Ancient'),
              (14, 1, 'Games'),
              (15, 1, 'Mathematics'),
              (16, 1, 'Inventions'),
              (17, 1, 'Botany'),
              (18, 1, 'Health'),
              (19, 1, 'Nature'),
              (20, 1, 'Language'),
              (21, 1, 'Architecture'),
              (22, 1, 'Earth'),
              (23, 1, 'Astronomy'),
              (24, 1, 'Forensics'),
              (25, 1, 'Funny'),
              (26, 1, 'Linguistics'),
              (27, 1, 'Conservation'),
              (28, 1, 'Medicine'),
              (29, 1, 'Human Body'),
              (30, 1, 'Psychology'),
              
              -- Quote Categories
              (101, 2, 'Motivation'),
              (102, 2, 'Opportunity'),
              (103, 2, 'Future'),
              (104, 2, 'Success'),
              (105, 2, 'Failure'),
              (106, 2, 'Courage'),
              (107, 2, 'Fear'),
              (108, 2, 'Innovation'),
              (109, 2, 'Wisdom'),
              (110, 2, 'Knowledge'),
              (111, 2, 'Persistence'),
              (112, 2, 'Progress'),
              (113, 2, 'Challenge'),
              (114, 2, 'Resilience'),
              (115, 2, 'Doubt'),
              (116, 2, 'Limitation'),
              (117, 2, 'Planning'),
              (118, 2, 'Risk'),
              (119, 2, 'Exploration'),
              (120, 2, 'Achievement'),
              (121, 2, 'Journey'),
              (122, 2, 'Starting'),
              (123, 2, 'Change'),
              (124, 2, 'Authenticity'),
              (125, 2, 'Self'),
              (126, 2, 'Self-Improvement'),
              (127, 2, 'Personal Growth'),
              (128, 2, 'Value'),
              (129, 2, 'Belief'),
              (130, 2, 'Confidence'),
              (131, 2, 'Action'),
              (132, 2, 'Helpfulness'),
              (133, 2, 'Kindness'),
              (134, 2, 'Friendship'),
              (135, 2, 'Relationships'),
              (136, 2, 'Happiness'),
              (137, 2, 'Contentment'),
              (138, 2, 'Learning'),
              (139, 2, 'Empathy'),
              (140, 2, 'Greatness'),
              (141, 2, 'Possibility'),
              (142, 2, 'Limits'),
              (143, 2, 'Dreams'),
              (144, 2, 'Regret'),
              (145, 2, 'Empowerment'),
              (146, 2, 'Life'),
              (147, 2, 'Burden'),
              (148, 2, 'Decision'),
              (149, 2, 'Work'),
              (150, 2, 'Passion'),
              (151, 2, 'Chaos'),
              (152, 2, 'Helping'),
              (153, 2, 'Wealth'),
              (154, 2, 'Understanding'),
              (155, 2, 'Perseverance'),
              (156, 2, 'Perspective'),
              (157, 2, 'Identity'))
AS SOURCE (CategoryId, CategoryTypeId, CategoryName)
ON TARGET.CategoryId = SOURCE.CategoryId
WHEN MATCHED THEN UPDATE SET TARGET.CategoryName   = SOURCE.CategoryName,
                             TARGET.CategoryTypeId = SOURCE.CategoryTypeId
WHEN NOT MATCHED BY TARGET THEN INSERT (CategoryId,
                                        CategoryTypeId,
                                        CategoryName)
                                VALUES (SOURCE.CategoryId,
                                        SOURCE.CategoryTypeId,
                                        SOURCE.CategoryName)
WHEN NOT MATCHED BY SOURCE THEN DELETE;
GO

SET IDENTITY_INSERT dbo.Category OFF
GO